spring.application.name=reconciliation

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/RRDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA - validate means Hibernate checks schema matches entities, but does NOT create/alter tables
# Flyway owns all DDL changes instead
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# This tells Hibernate to depend on Flyway bean before initializing
#spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=debug
#spring.flyway.baseline-on-migrate=false
#spring.flyway.user=postgres
#spring.flyway.password=root

#logging.level.root=info

reconciliation.match.tolerance=0.01
