spring.application.name=reconciliation
spring.datasource.url=jdbc:postgresql://localhost:5432/RRDB
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
